Txn builder fees operation
FindoraNetwork/platform pull request #216
Opened 2022-02-10 01:55 UTC by Serge-Juarez

The test that I've witten

axfr_create_verify_unit_positive_tests_with_fees_remainder
axfr_create_verify_unit_positive_tests_with_fees

for function "add_operation_anon_transfer_fees_remainder" and "add_operation_anon_transfer_fees"

have the problem about running in multiple threats, nontheless they passed if they run using a unique threat.

I know that it is difficult to manage two different function from the CLI, so I think we can consider the one with fees and remainder as the best candidate, but I also wrote a version considering only fees.

2022-02-10 20:25 UTC, akhilpeddireddy requested changes

2022-02-10 20:25 UTC, akhilpeddireddy commented on src/components/finutils/src/txn_builder/mod.rs
> +    pub fn add_operation_anon_transfer_fees(
@Serge-Juarez I think the functionality of this operation is redundant to add_operation_anon_transfer, as the part that is different here is the additional assertion `assert_eq!(sum_input, sum_output + fees)`, but I believe that is taken care of by the proof itself at the step where we use `gen_anon_xfr_body`. In my opinion we could remove this function and stick to `add_operation_anon_transfer` for the cases where remainder is not needed to be added, and the pre-requisite for it is to pre-check the amount equations are balanced.

2022-02-10 20:25 UTC, akhilpeddireddy commented on src/components/finutils/src/txn_builder/mod.rs
> +    fn axfr_create_verify_unit_positive_tests_with_fees_remainder() {
The axfr unit tests on txn_builder are taking a long time to run (~5 mins) and might be an issue with the CI when upstreamed, so I suggest we include the remainder part in the existing `axfr_create_verify_unit_positive_tests_with_fees` test instead of having another new test. Since all the steps in `add_operation_anon_transfer` are also a part of `add_operation_anon_transfer_fees_remainder` , the working of the later should mean the former also works, albeit with a pre-computed balanced amounts, and having a unit test for it might not be that critical in my opinion.

2022-02-11 01:33 UTC, Serge-Juarez commented on src/components/finutils/src/txn_builder/mod.rs
> +    fn axfr_create_verify_unit_positive_tests_with_fees_remainder() {
I agree with the two suggestions, hence I will proceed to modify the code.

2022-03-17 08:26 UTC, closed without merging