add clean_aux()
FindoraNetwork/platform pull request #563
Opened 2022-09-26 10:18 UTC by HarryLiIsMe

* **make sure that you have executed all the following process and no errors occur**
  - [ ] make fmt
  - [ ] make lint
  - [ ] make test

* **The major changes of this PR**

* **The major impacts of this PR**
  - [ ] Impact WASM?
  - [ ] Impact Web3 API?
  - [ ] Impact mainnet data compatibility?

* **Extra documentations**

2022-09-29 02:57 UTC, ws4charlie commented on src/components/config/src/findora/mod.rs
> +                .arg_from_usage("--trace=[ABCId Trace]")
EVM Tracing Period, in days

2022-09-29 02:58 UTC, ws4charlie commented on src/components/config/src/findora/mod.rs
> +                .arg_from_usage("--fresh=[ABCId Fresh]")
EVM Tracing from fresh

2022-09-29 03:00 UTC, ws4charlie commented on tools/devnet/env.sh
> +DEFAULT_BLOCK_INTERVAL="16"
Can we leave this `2` second block time as is so that the tests can run fast?

2022-09-29 04:28 UTC, HarryLiIsMe commented on src/components/config/src/findora/mod.rs
> +                .arg_from_usage("--trace=[ABCId Trace]")
ok, I have done it.

2022-09-29 04:28 UTC, HarryLiIsMe commented on src/components/config/src/findora/mod.rs
> +                .arg_from_usage("--fresh=[ABCId Fresh]")
ok, I have done it.

2022-09-29 04:28 UTC, HarryLiIsMe commented on tools/devnet/env.sh
> +DEFAULT_BLOCK_INTERVAL="16"
ok, I have modified it.

2022-10-14 16:45 UTC, ws4charlie approved these changes
looks good

2022-11-16 00:55 UTC, simonjiao requested changes

2022-11-16 05:53 UTC, simonjiao approved these changes

2023-01-19 08:48 UTC, closed without merging