Fix delegation rewards overflow using bigint.
FindoraNetwork/platform pull request #98
Opened 2021-11-06 12:02 UTC by tiannian

* **make sure that you have executed all the following process and no errors occur**
  - [X] make fmt
  - [X] make lint
  - [X] make test

* **The major changes of this PR**

use `biguint` instead of `u128`

* **Extra documentations**

2021-11-07 15:03 UTC, ktmlm requested changes

2021-11-07 15:03 UTC, ktmlm commented on src/ledger/src/staking/mod.rs
> +    const OVERFLOW_FIX_HEIGHT: BlockHeight = 122_5000;
This height has become history on the chain

2021-11-07 16:26 UTC, tiannian commented on src/ledger/src/staking/mod.rs
> +    const OVERFLOW_FIX_HEIGHT: BlockHeight = 122_5000;
I change it to 123_2000, about 2021-11-08 23:45

2021-11-08 02:40 UTC, malefooo approved these changes

2021-11-08 03:52 UTC, merged